# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\SOFT\c++\Exercise\BattleCity

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\SOFT\c++\Exercise\BattleCity

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\SOFT\c++\Exercise\BattleCity\CMakeFiles D:\SOFT\c++\Exercise\BattleCity\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\SOFT\c++\Exercise\BattleCity\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BattleCity

# Build rule for target.
BattleCity: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 BattleCity
.PHONY : BattleCity

# fast build rule for target.
BattleCity/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/build
.PHONY : BattleCity/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f external\glfw\src\CMakeFiles\glfw.dir\build.make external/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f external\glfw\src\CMakeFiles\update_mappings.dir\build.make external/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f external\glad\CMakeFiles\glad.dir\build.make external/glad/CMakeFiles/glad.dir/build
.PHONY : glad/fast

src/Game/Game.obj: src/Game/Game.cpp.obj
.PHONY : src/Game/Game.obj

# target to build an object file
src/Game/Game.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/Game.cpp.obj
.PHONY : src/Game/Game.cpp.obj

src/Game/Game.i: src/Game/Game.cpp.i
.PHONY : src/Game/Game.i

# target to preprocess a source file
src/Game/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/Game.cpp.i
.PHONY : src/Game/Game.cpp.i

src/Game/Game.s: src/Game/Game.cpp.s
.PHONY : src/Game/Game.s

# target to generate assembly for a file
src/Game/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/Game.cpp.s
.PHONY : src/Game/Game.cpp.s

src/Game/GameObjects/BetonWall.obj: src/Game/GameObjects/BetonWall.cpp.obj
.PHONY : src/Game/GameObjects/BetonWall.obj

# target to build an object file
src/Game/GameObjects/BetonWall.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/BetonWall.cpp.obj
.PHONY : src/Game/GameObjects/BetonWall.cpp.obj

src/Game/GameObjects/BetonWall.i: src/Game/GameObjects/BetonWall.cpp.i
.PHONY : src/Game/GameObjects/BetonWall.i

# target to preprocess a source file
src/Game/GameObjects/BetonWall.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/BetonWall.cpp.i
.PHONY : src/Game/GameObjects/BetonWall.cpp.i

src/Game/GameObjects/BetonWall.s: src/Game/GameObjects/BetonWall.cpp.s
.PHONY : src/Game/GameObjects/BetonWall.s

# target to generate assembly for a file
src/Game/GameObjects/BetonWall.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/BetonWall.cpp.s
.PHONY : src/Game/GameObjects/BetonWall.cpp.s

src/Game/GameObjects/Border.obj: src/Game/GameObjects/Border.cpp.obj
.PHONY : src/Game/GameObjects/Border.obj

# target to build an object file
src/Game/GameObjects/Border.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/Border.cpp.obj
.PHONY : src/Game/GameObjects/Border.cpp.obj

src/Game/GameObjects/Border.i: src/Game/GameObjects/Border.cpp.i
.PHONY : src/Game/GameObjects/Border.i

# target to preprocess a source file
src/Game/GameObjects/Border.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/Border.cpp.i
.PHONY : src/Game/GameObjects/Border.cpp.i

src/Game/GameObjects/Border.s: src/Game/GameObjects/Border.cpp.s
.PHONY : src/Game/GameObjects/Border.s

# target to generate assembly for a file
src/Game/GameObjects/Border.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/Border.cpp.s
.PHONY : src/Game/GameObjects/Border.cpp.s

src/Game/GameObjects/BrickWall.obj: src/Game/GameObjects/BrickWall.cpp.obj
.PHONY : src/Game/GameObjects/BrickWall.obj

# target to build an object file
src/Game/GameObjects/BrickWall.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/BrickWall.cpp.obj
.PHONY : src/Game/GameObjects/BrickWall.cpp.obj

src/Game/GameObjects/BrickWall.i: src/Game/GameObjects/BrickWall.cpp.i
.PHONY : src/Game/GameObjects/BrickWall.i

# target to preprocess a source file
src/Game/GameObjects/BrickWall.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/BrickWall.cpp.i
.PHONY : src/Game/GameObjects/BrickWall.cpp.i

src/Game/GameObjects/BrickWall.s: src/Game/GameObjects/BrickWall.cpp.s
.PHONY : src/Game/GameObjects/BrickWall.s

# target to generate assembly for a file
src/Game/GameObjects/BrickWall.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/BrickWall.cpp.s
.PHONY : src/Game/GameObjects/BrickWall.cpp.s

src/Game/GameObjects/Bullet.obj: src/Game/GameObjects/Bullet.cpp.obj
.PHONY : src/Game/GameObjects/Bullet.obj

# target to build an object file
src/Game/GameObjects/Bullet.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/Bullet.cpp.obj
.PHONY : src/Game/GameObjects/Bullet.cpp.obj

src/Game/GameObjects/Bullet.i: src/Game/GameObjects/Bullet.cpp.i
.PHONY : src/Game/GameObjects/Bullet.i

# target to preprocess a source file
src/Game/GameObjects/Bullet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/Bullet.cpp.i
.PHONY : src/Game/GameObjects/Bullet.cpp.i

src/Game/GameObjects/Bullet.s: src/Game/GameObjects/Bullet.cpp.s
.PHONY : src/Game/GameObjects/Bullet.s

# target to generate assembly for a file
src/Game/GameObjects/Bullet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/Bullet.cpp.s
.PHONY : src/Game/GameObjects/Bullet.cpp.s

src/Game/GameObjects/Eagle.obj: src/Game/GameObjects/Eagle.cpp.obj
.PHONY : src/Game/GameObjects/Eagle.obj

# target to build an object file
src/Game/GameObjects/Eagle.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/Eagle.cpp.obj
.PHONY : src/Game/GameObjects/Eagle.cpp.obj

src/Game/GameObjects/Eagle.i: src/Game/GameObjects/Eagle.cpp.i
.PHONY : src/Game/GameObjects/Eagle.i

# target to preprocess a source file
src/Game/GameObjects/Eagle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/Eagle.cpp.i
.PHONY : src/Game/GameObjects/Eagle.cpp.i

src/Game/GameObjects/Eagle.s: src/Game/GameObjects/Eagle.cpp.s
.PHONY : src/Game/GameObjects/Eagle.s

# target to generate assembly for a file
src/Game/GameObjects/Eagle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/Eagle.cpp.s
.PHONY : src/Game/GameObjects/Eagle.cpp.s

src/Game/GameObjects/IGameObject.obj: src/Game/GameObjects/IGameObject.cpp.obj
.PHONY : src/Game/GameObjects/IGameObject.obj

# target to build an object file
src/Game/GameObjects/IGameObject.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/IGameObject.cpp.obj
.PHONY : src/Game/GameObjects/IGameObject.cpp.obj

src/Game/GameObjects/IGameObject.i: src/Game/GameObjects/IGameObject.cpp.i
.PHONY : src/Game/GameObjects/IGameObject.i

# target to preprocess a source file
src/Game/GameObjects/IGameObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/IGameObject.cpp.i
.PHONY : src/Game/GameObjects/IGameObject.cpp.i

src/Game/GameObjects/IGameObject.s: src/Game/GameObjects/IGameObject.cpp.s
.PHONY : src/Game/GameObjects/IGameObject.s

# target to generate assembly for a file
src/Game/GameObjects/IGameObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/IGameObject.cpp.s
.PHONY : src/Game/GameObjects/IGameObject.cpp.s

src/Game/GameObjects/Ice.obj: src/Game/GameObjects/Ice.cpp.obj
.PHONY : src/Game/GameObjects/Ice.obj

# target to build an object file
src/Game/GameObjects/Ice.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/Ice.cpp.obj
.PHONY : src/Game/GameObjects/Ice.cpp.obj

src/Game/GameObjects/Ice.i: src/Game/GameObjects/Ice.cpp.i
.PHONY : src/Game/GameObjects/Ice.i

# target to preprocess a source file
src/Game/GameObjects/Ice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/Ice.cpp.i
.PHONY : src/Game/GameObjects/Ice.cpp.i

src/Game/GameObjects/Ice.s: src/Game/GameObjects/Ice.cpp.s
.PHONY : src/Game/GameObjects/Ice.s

# target to generate assembly for a file
src/Game/GameObjects/Ice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/Ice.cpp.s
.PHONY : src/Game/GameObjects/Ice.cpp.s

src/Game/GameObjects/Tank.obj: src/Game/GameObjects/Tank.cpp.obj
.PHONY : src/Game/GameObjects/Tank.obj

# target to build an object file
src/Game/GameObjects/Tank.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/Tank.cpp.obj
.PHONY : src/Game/GameObjects/Tank.cpp.obj

src/Game/GameObjects/Tank.i: src/Game/GameObjects/Tank.cpp.i
.PHONY : src/Game/GameObjects/Tank.i

# target to preprocess a source file
src/Game/GameObjects/Tank.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/Tank.cpp.i
.PHONY : src/Game/GameObjects/Tank.cpp.i

src/Game/GameObjects/Tank.s: src/Game/GameObjects/Tank.cpp.s
.PHONY : src/Game/GameObjects/Tank.s

# target to generate assembly for a file
src/Game/GameObjects/Tank.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/Tank.cpp.s
.PHONY : src/Game/GameObjects/Tank.cpp.s

src/Game/GameObjects/Trees.obj: src/Game/GameObjects/Trees.cpp.obj
.PHONY : src/Game/GameObjects/Trees.obj

# target to build an object file
src/Game/GameObjects/Trees.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/Trees.cpp.obj
.PHONY : src/Game/GameObjects/Trees.cpp.obj

src/Game/GameObjects/Trees.i: src/Game/GameObjects/Trees.cpp.i
.PHONY : src/Game/GameObjects/Trees.i

# target to preprocess a source file
src/Game/GameObjects/Trees.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/Trees.cpp.i
.PHONY : src/Game/GameObjects/Trees.cpp.i

src/Game/GameObjects/Trees.s: src/Game/GameObjects/Trees.cpp.s
.PHONY : src/Game/GameObjects/Trees.s

# target to generate assembly for a file
src/Game/GameObjects/Trees.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/Trees.cpp.s
.PHONY : src/Game/GameObjects/Trees.cpp.s

src/Game/GameObjects/Water.obj: src/Game/GameObjects/Water.cpp.obj
.PHONY : src/Game/GameObjects/Water.obj

# target to build an object file
src/Game/GameObjects/Water.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/Water.cpp.obj
.PHONY : src/Game/GameObjects/Water.cpp.obj

src/Game/GameObjects/Water.i: src/Game/GameObjects/Water.cpp.i
.PHONY : src/Game/GameObjects/Water.i

# target to preprocess a source file
src/Game/GameObjects/Water.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/Water.cpp.i
.PHONY : src/Game/GameObjects/Water.cpp.i

src/Game/GameObjects/Water.s: src/Game/GameObjects/Water.cpp.s
.PHONY : src/Game/GameObjects/Water.s

# target to generate assembly for a file
src/Game/GameObjects/Water.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/GameObjects/Water.cpp.s
.PHONY : src/Game/GameObjects/Water.cpp.s

src/Game/Level.obj: src/Game/Level.cpp.obj
.PHONY : src/Game/Level.obj

# target to build an object file
src/Game/Level.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/Level.cpp.obj
.PHONY : src/Game/Level.cpp.obj

src/Game/Level.i: src/Game/Level.cpp.i
.PHONY : src/Game/Level.i

# target to preprocess a source file
src/Game/Level.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/Level.cpp.i
.PHONY : src/Game/Level.cpp.i

src/Game/Level.s: src/Game/Level.cpp.s
.PHONY : src/Game/Level.s

# target to generate assembly for a file
src/Game/Level.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Game/Level.cpp.s
.PHONY : src/Game/Level.cpp.s

src/PhysicsEngine/PhysicsEngine.obj: src/PhysicsEngine/PhysicsEngine.cpp.obj
.PHONY : src/PhysicsEngine/PhysicsEngine.obj

# target to build an object file
src/PhysicsEngine/PhysicsEngine.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/PhysicsEngine/PhysicsEngine.cpp.obj
.PHONY : src/PhysicsEngine/PhysicsEngine.cpp.obj

src/PhysicsEngine/PhysicsEngine.i: src/PhysicsEngine/PhysicsEngine.cpp.i
.PHONY : src/PhysicsEngine/PhysicsEngine.i

# target to preprocess a source file
src/PhysicsEngine/PhysicsEngine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/PhysicsEngine/PhysicsEngine.cpp.i
.PHONY : src/PhysicsEngine/PhysicsEngine.cpp.i

src/PhysicsEngine/PhysicsEngine.s: src/PhysicsEngine/PhysicsEngine.cpp.s
.PHONY : src/PhysicsEngine/PhysicsEngine.s

# target to generate assembly for a file
src/PhysicsEngine/PhysicsEngine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/PhysicsEngine/PhysicsEngine.cpp.s
.PHONY : src/PhysicsEngine/PhysicsEngine.cpp.s

src/Renderer/IndexBuffer.obj: src/Renderer/IndexBuffer.cpp.obj
.PHONY : src/Renderer/IndexBuffer.obj

# target to build an object file
src/Renderer/IndexBuffer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Renderer/IndexBuffer.cpp.obj
.PHONY : src/Renderer/IndexBuffer.cpp.obj

src/Renderer/IndexBuffer.i: src/Renderer/IndexBuffer.cpp.i
.PHONY : src/Renderer/IndexBuffer.i

# target to preprocess a source file
src/Renderer/IndexBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Renderer/IndexBuffer.cpp.i
.PHONY : src/Renderer/IndexBuffer.cpp.i

src/Renderer/IndexBuffer.s: src/Renderer/IndexBuffer.cpp.s
.PHONY : src/Renderer/IndexBuffer.s

# target to generate assembly for a file
src/Renderer/IndexBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Renderer/IndexBuffer.cpp.s
.PHONY : src/Renderer/IndexBuffer.cpp.s

src/Renderer/Renderer.obj: src/Renderer/Renderer.cpp.obj
.PHONY : src/Renderer/Renderer.obj

# target to build an object file
src/Renderer/Renderer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Renderer/Renderer.cpp.obj
.PHONY : src/Renderer/Renderer.cpp.obj

src/Renderer/Renderer.i: src/Renderer/Renderer.cpp.i
.PHONY : src/Renderer/Renderer.i

# target to preprocess a source file
src/Renderer/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Renderer/Renderer.cpp.i
.PHONY : src/Renderer/Renderer.cpp.i

src/Renderer/Renderer.s: src/Renderer/Renderer.cpp.s
.PHONY : src/Renderer/Renderer.s

# target to generate assembly for a file
src/Renderer/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Renderer/Renderer.cpp.s
.PHONY : src/Renderer/Renderer.cpp.s

src/Renderer/ShaderProgram.obj: src/Renderer/ShaderProgram.cpp.obj
.PHONY : src/Renderer/ShaderProgram.obj

# target to build an object file
src/Renderer/ShaderProgram.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Renderer/ShaderProgram.cpp.obj
.PHONY : src/Renderer/ShaderProgram.cpp.obj

src/Renderer/ShaderProgram.i: src/Renderer/ShaderProgram.cpp.i
.PHONY : src/Renderer/ShaderProgram.i

# target to preprocess a source file
src/Renderer/ShaderProgram.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Renderer/ShaderProgram.cpp.i
.PHONY : src/Renderer/ShaderProgram.cpp.i

src/Renderer/ShaderProgram.s: src/Renderer/ShaderProgram.cpp.s
.PHONY : src/Renderer/ShaderProgram.s

# target to generate assembly for a file
src/Renderer/ShaderProgram.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Renderer/ShaderProgram.cpp.s
.PHONY : src/Renderer/ShaderProgram.cpp.s

src/Renderer/Sprite.obj: src/Renderer/Sprite.cpp.obj
.PHONY : src/Renderer/Sprite.obj

# target to build an object file
src/Renderer/Sprite.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Renderer/Sprite.cpp.obj
.PHONY : src/Renderer/Sprite.cpp.obj

src/Renderer/Sprite.i: src/Renderer/Sprite.cpp.i
.PHONY : src/Renderer/Sprite.i

# target to preprocess a source file
src/Renderer/Sprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Renderer/Sprite.cpp.i
.PHONY : src/Renderer/Sprite.cpp.i

src/Renderer/Sprite.s: src/Renderer/Sprite.cpp.s
.PHONY : src/Renderer/Sprite.s

# target to generate assembly for a file
src/Renderer/Sprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Renderer/Sprite.cpp.s
.PHONY : src/Renderer/Sprite.cpp.s

src/Renderer/SpriteAnimator.obj: src/Renderer/SpriteAnimator.cpp.obj
.PHONY : src/Renderer/SpriteAnimator.obj

# target to build an object file
src/Renderer/SpriteAnimator.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Renderer/SpriteAnimator.cpp.obj
.PHONY : src/Renderer/SpriteAnimator.cpp.obj

src/Renderer/SpriteAnimator.i: src/Renderer/SpriteAnimator.cpp.i
.PHONY : src/Renderer/SpriteAnimator.i

# target to preprocess a source file
src/Renderer/SpriteAnimator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Renderer/SpriteAnimator.cpp.i
.PHONY : src/Renderer/SpriteAnimator.cpp.i

src/Renderer/SpriteAnimator.s: src/Renderer/SpriteAnimator.cpp.s
.PHONY : src/Renderer/SpriteAnimator.s

# target to generate assembly for a file
src/Renderer/SpriteAnimator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Renderer/SpriteAnimator.cpp.s
.PHONY : src/Renderer/SpriteAnimator.cpp.s

src/Renderer/Texture2D.obj: src/Renderer/Texture2D.cpp.obj
.PHONY : src/Renderer/Texture2D.obj

# target to build an object file
src/Renderer/Texture2D.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Renderer/Texture2D.cpp.obj
.PHONY : src/Renderer/Texture2D.cpp.obj

src/Renderer/Texture2D.i: src/Renderer/Texture2D.cpp.i
.PHONY : src/Renderer/Texture2D.i

# target to preprocess a source file
src/Renderer/Texture2D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Renderer/Texture2D.cpp.i
.PHONY : src/Renderer/Texture2D.cpp.i

src/Renderer/Texture2D.s: src/Renderer/Texture2D.cpp.s
.PHONY : src/Renderer/Texture2D.s

# target to generate assembly for a file
src/Renderer/Texture2D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Renderer/Texture2D.cpp.s
.PHONY : src/Renderer/Texture2D.cpp.s

src/Renderer/VertexArray.obj: src/Renderer/VertexArray.cpp.obj
.PHONY : src/Renderer/VertexArray.obj

# target to build an object file
src/Renderer/VertexArray.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Renderer/VertexArray.cpp.obj
.PHONY : src/Renderer/VertexArray.cpp.obj

src/Renderer/VertexArray.i: src/Renderer/VertexArray.cpp.i
.PHONY : src/Renderer/VertexArray.i

# target to preprocess a source file
src/Renderer/VertexArray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Renderer/VertexArray.cpp.i
.PHONY : src/Renderer/VertexArray.cpp.i

src/Renderer/VertexArray.s: src/Renderer/VertexArray.cpp.s
.PHONY : src/Renderer/VertexArray.s

# target to generate assembly for a file
src/Renderer/VertexArray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Renderer/VertexArray.cpp.s
.PHONY : src/Renderer/VertexArray.cpp.s

src/Renderer/VertexBuffer.obj: src/Renderer/VertexBuffer.cpp.obj
.PHONY : src/Renderer/VertexBuffer.obj

# target to build an object file
src/Renderer/VertexBuffer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Renderer/VertexBuffer.cpp.obj
.PHONY : src/Renderer/VertexBuffer.cpp.obj

src/Renderer/VertexBuffer.i: src/Renderer/VertexBuffer.cpp.i
.PHONY : src/Renderer/VertexBuffer.i

# target to preprocess a source file
src/Renderer/VertexBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Renderer/VertexBuffer.cpp.i
.PHONY : src/Renderer/VertexBuffer.cpp.i

src/Renderer/VertexBuffer.s: src/Renderer/VertexBuffer.cpp.s
.PHONY : src/Renderer/VertexBuffer.s

# target to generate assembly for a file
src/Renderer/VertexBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Renderer/VertexBuffer.cpp.s
.PHONY : src/Renderer/VertexBuffer.cpp.s

src/Renderer/VertexBufferLayout.obj: src/Renderer/VertexBufferLayout.cpp.obj
.PHONY : src/Renderer/VertexBufferLayout.obj

# target to build an object file
src/Renderer/VertexBufferLayout.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Renderer/VertexBufferLayout.cpp.obj
.PHONY : src/Renderer/VertexBufferLayout.cpp.obj

src/Renderer/VertexBufferLayout.i: src/Renderer/VertexBufferLayout.cpp.i
.PHONY : src/Renderer/VertexBufferLayout.i

# target to preprocess a source file
src/Renderer/VertexBufferLayout.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Renderer/VertexBufferLayout.cpp.i
.PHONY : src/Renderer/VertexBufferLayout.cpp.i

src/Renderer/VertexBufferLayout.s: src/Renderer/VertexBufferLayout.cpp.s
.PHONY : src/Renderer/VertexBufferLayout.s

# target to generate assembly for a file
src/Renderer/VertexBufferLayout.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Renderer/VertexBufferLayout.cpp.s
.PHONY : src/Renderer/VertexBufferLayout.cpp.s

src/Resources/ResourceManager.obj: src/Resources/ResourceManager.cpp.obj
.PHONY : src/Resources/ResourceManager.obj

# target to build an object file
src/Resources/ResourceManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Resources/ResourceManager.cpp.obj
.PHONY : src/Resources/ResourceManager.cpp.obj

src/Resources/ResourceManager.i: src/Resources/ResourceManager.cpp.i
.PHONY : src/Resources/ResourceManager.i

# target to preprocess a source file
src/Resources/ResourceManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Resources/ResourceManager.cpp.i
.PHONY : src/Resources/ResourceManager.cpp.i

src/Resources/ResourceManager.s: src/Resources/ResourceManager.cpp.s
.PHONY : src/Resources/ResourceManager.s

# target to generate assembly for a file
src/Resources/ResourceManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/Resources/ResourceManager.cpp.s
.PHONY : src/Resources/ResourceManager.cpp.s

src/System/Timer.obj: src/System/Timer.cpp.obj
.PHONY : src/System/Timer.obj

# target to build an object file
src/System/Timer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/System/Timer.cpp.obj
.PHONY : src/System/Timer.cpp.obj

src/System/Timer.i: src/System/Timer.cpp.i
.PHONY : src/System/Timer.i

# target to preprocess a source file
src/System/Timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/System/Timer.cpp.i
.PHONY : src/System/Timer.cpp.i

src/System/Timer.s: src/System/Timer.cpp.s
.PHONY : src/System/Timer.s

# target to generate assembly for a file
src/System/Timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/System/Timer.cpp.s
.PHONY : src/System/Timer.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BattleCity.dir\build.make CMakeFiles/BattleCity.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... update_mappings
	@echo ... BattleCity
	@echo ... glad
	@echo ... glfw
	@echo ... src/Game/Game.obj
	@echo ... src/Game/Game.i
	@echo ... src/Game/Game.s
	@echo ... src/Game/GameObjects/BetonWall.obj
	@echo ... src/Game/GameObjects/BetonWall.i
	@echo ... src/Game/GameObjects/BetonWall.s
	@echo ... src/Game/GameObjects/Border.obj
	@echo ... src/Game/GameObjects/Border.i
	@echo ... src/Game/GameObjects/Border.s
	@echo ... src/Game/GameObjects/BrickWall.obj
	@echo ... src/Game/GameObjects/BrickWall.i
	@echo ... src/Game/GameObjects/BrickWall.s
	@echo ... src/Game/GameObjects/Bullet.obj
	@echo ... src/Game/GameObjects/Bullet.i
	@echo ... src/Game/GameObjects/Bullet.s
	@echo ... src/Game/GameObjects/Eagle.obj
	@echo ... src/Game/GameObjects/Eagle.i
	@echo ... src/Game/GameObjects/Eagle.s
	@echo ... src/Game/GameObjects/IGameObject.obj
	@echo ... src/Game/GameObjects/IGameObject.i
	@echo ... src/Game/GameObjects/IGameObject.s
	@echo ... src/Game/GameObjects/Ice.obj
	@echo ... src/Game/GameObjects/Ice.i
	@echo ... src/Game/GameObjects/Ice.s
	@echo ... src/Game/GameObjects/Tank.obj
	@echo ... src/Game/GameObjects/Tank.i
	@echo ... src/Game/GameObjects/Tank.s
	@echo ... src/Game/GameObjects/Trees.obj
	@echo ... src/Game/GameObjects/Trees.i
	@echo ... src/Game/GameObjects/Trees.s
	@echo ... src/Game/GameObjects/Water.obj
	@echo ... src/Game/GameObjects/Water.i
	@echo ... src/Game/GameObjects/Water.s
	@echo ... src/Game/Level.obj
	@echo ... src/Game/Level.i
	@echo ... src/Game/Level.s
	@echo ... src/PhysicsEngine/PhysicsEngine.obj
	@echo ... src/PhysicsEngine/PhysicsEngine.i
	@echo ... src/PhysicsEngine/PhysicsEngine.s
	@echo ... src/Renderer/IndexBuffer.obj
	@echo ... src/Renderer/IndexBuffer.i
	@echo ... src/Renderer/IndexBuffer.s
	@echo ... src/Renderer/Renderer.obj
	@echo ... src/Renderer/Renderer.i
	@echo ... src/Renderer/Renderer.s
	@echo ... src/Renderer/ShaderProgram.obj
	@echo ... src/Renderer/ShaderProgram.i
	@echo ... src/Renderer/ShaderProgram.s
	@echo ... src/Renderer/Sprite.obj
	@echo ... src/Renderer/Sprite.i
	@echo ... src/Renderer/Sprite.s
	@echo ... src/Renderer/SpriteAnimator.obj
	@echo ... src/Renderer/SpriteAnimator.i
	@echo ... src/Renderer/SpriteAnimator.s
	@echo ... src/Renderer/Texture2D.obj
	@echo ... src/Renderer/Texture2D.i
	@echo ... src/Renderer/Texture2D.s
	@echo ... src/Renderer/VertexArray.obj
	@echo ... src/Renderer/VertexArray.i
	@echo ... src/Renderer/VertexArray.s
	@echo ... src/Renderer/VertexBuffer.obj
	@echo ... src/Renderer/VertexBuffer.i
	@echo ... src/Renderer/VertexBuffer.s
	@echo ... src/Renderer/VertexBufferLayout.obj
	@echo ... src/Renderer/VertexBufferLayout.i
	@echo ... src/Renderer/VertexBufferLayout.s
	@echo ... src/Resources/ResourceManager.obj
	@echo ... src/Resources/ResourceManager.i
	@echo ... src/Resources/ResourceManager.s
	@echo ... src/System/Timer.obj
	@echo ... src/System/Timer.i
	@echo ... src/System/Timer.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

